# Generated by Django 5.2.8 on 2025-11-16 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20)),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('deposit', 'Проценты по вкладу'), ('transfer', 'Перевод'), ('business', 'Бизнес'), ('food', 'Продукты'), ('transport', 'Транспорт'), ('utilities', 'Коммунальные услуги'), ('rent', 'Аренда'), ('clothes', 'Одежда'), ('fun', 'Развлечения')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
